drop table if exists member CASCADE;
create table member
(
    id   bigint generated by default as identity,
    email varchar(255),
    username varchar(255),
    password varchar(255),
    primary key (id)
);

drop table if exists project CASCADE;
create table project
(
	id	bigint generated by default as identity,
	owner varchar(255) not null,
	name varchar(255) not null,
	description varchar(255),
	visibility varchar(100),
	create_time varchar(255),
	update_time varchar(255),
	primary key (id)
);

insert into project(owner, name, description, visibility, createtime)
values('choyi', 'first-project', 'this is my first project', 'public', '202108241730'),
('choyi', 'second-project', 'Lorem Ipsum awesome project', 'public', '202108241732'),
('choyi', 'third-project', 'java web application', 'public', '202108241736');