drop table if exists members CASCADE;
create table members
(
    id   bigint generated by default as identity,
    email varchar(255),
    username varchar(255),
    password varchar(255),
	enabled boolean default TRUE not null,
    primary key (id)
);

create table authorities
(
	id bigint generated by default as identity,
	username varchar(255) not null,
	authority varchar(50) not null,
	constraint fk_authorities_members foreign key(username) references members(username)
);
create unique index ix_auth_username on authorities (username, authority);

drop table if exists project CASCADE;
create table project
(
	id	bigint generated by default as identity,
	owner varchar(255) not null,
	name varchar(255) not null,
	description varchar(255),
	visibility varchar(100),
	create_time timestamp default current_timestamp not null,
	update_time timestamp default current_timestamp not null,
	primary key (id)
);


drop table if exists FILE_METADATA CASCADE;
create table FILE_METADATA
(
	id bigint generated by default as identity,
	file_id bigint,
	repository_id bigint,
	upload_id bigint,
	name varchar(255),
	size bigint,
	content_type varchar(255),
	directory varchar(255),
	primary key (id)
);

insert into project(owner, name, description, visibility, create_time)
values('choyi', 'first-project', 'this is my first project', 'public', parseDateTime('20210824173000', 'yyyyMMddHHmmss')),
('choyi', 'second-project', 'Lorem Ipsum awesome project', 'public', parseDateTime('20210824173200', 'yyyyMMddHHmmss')),
('choyi', 'third-project', 'java web application', 'public', parseDateTime('20210824173400', 'yyyyMMddHHmmss'));

insert into members(email, username, password, enabled) values('mchoisay@gmail.com', 'choyi', '$2a$12$gwO/Cpe0EgkI7SYAX2bv1e.BNt/BejbTHd4ymb20kdfw2rrIZCbjm', TRUE);
insert into authorities(username, authority) values('choyi', 'ROLE_USER');